# Generated by Django 4.2.5 on 2023-10-06 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_exam_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('I', 'Image Exam'), ('B', 'Blood Exam')], max_length=1)),
                ('price', models.FloatField()),
                ('avaliable', models.BooleanField(default=True)),
                ('initial_hour', models.IntegerField()),
                ('final_hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='exam_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('I', 'Image Exam'), ('B', 'Blood Exam')], max_length=1)),
                ('price', models.FloatField()),
                ('avaliable', models.BooleanField(default=True)),
                ('initial_hour', models.IntegerField()),
                ('final_hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='exam_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Review'), ('F', 'Finished')], max_length=2)),
                ('result', models.FileField(blank=True, null=True, upload_to='result')),
                ('password_required', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=6, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labexam.exam_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='exam_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('exam', models.ManyToManyField(to='labexam.exam_request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
]
